- name: Monthly Production Cycle
  path: '/production/'
  subnav:
    - name: 'General Procedures'
      path: '/production/'
    - name: 'Timeline'
      path: '/production/timeline'
- name: Interviews
  path: '/production/'
  subnav:
    - name: 'Building a Dossier'
      path: '/production/'
    - name: 'How to Transcribe'
      path: '/production/'
    - name: 'Correct Interview Formatting'
      path: '/production/'
- name: Editorial Supplement
  path: '/production/'
  subnav:
    - name: 'House Style'
      path: '/production/'
    - name: 'Copyediting Procedure'
      path: '/production/'
    - name: 'Proofreader’s Marks'
      path: '/production/'
- name: Images
  path: '/production/'
  subnav:
    - name: 'Acquiring Press Images'
      path: '/production/'
    - name: 'Preparing Images for Print'
      path: '/production/'
    - name: 'Preparing Images for Web'
      path: '/production/'
    - name: 'Captions'
      path: '/production/'
    - name: 'Image Rights and Restrictions'
      path: '/production/'
- name: Web Guide
  path: '/production/'
  subnav:
    - name: 'Web Standards'
      path: '/production/'
    - name: 'HTML shortcuts'
      path: '/production/'
    - name: 'Checklist for uploading articles'
      path: '/production/'
- name: During Layout
  path: '/production/'
  subnav:
    - name: 'Building the Table of Contents'
      path: '/production/'
    - name: 'Proofing Galleys'
      path: '/production/'
    - name: 'Using InCopy'
      path: '/production/'
    - name: 'Entering Final Changes'
      path: '/production/'
    - name: 'Final Checklist before going to print'
      path: '/production/'
