# ===========================

# How to set up Netlify CMS to work with GitHub Pages
# 1. go to https://github.com/organizations/brooklynrail/settings/applications
# 2. Create a new OAuth App and enter
  # - the name of the site
  # - the primary URL for the site
  # - a short description of the site
  # - authorization callback URL `https://api.netlify.com/auth/done`

# For reference:
# - https://cnly.github.io/2018/04/14/just-3-steps-adding-netlify-cms-to-existing-github-pages-site-within-10-minutes.html
# - https://sb-ph.com/posts/2019/01/working-with-netlify-cms-and-github-pages/

# ===========================

display_url: https://brooklynrail.github.io/brooklynrail-handbook/
site_url: https://brooklynrail.github.io/brooklynrail-handbook/

# logo_url — sets the logo in the /admin
logo_url: https://brooklynrail.github.io/brooklynrail-handbook/assets/img/br-diversity.svg

# Backend and connections

backend:
  name: github
  repo: brooklynrail/brooklynrail-handbook
  # api_root: https://api.github.com
  site_domain: brooklynrail-handbook.netlify.com
  base_url: https://api.netlify.com
  # auth_endpoint: auth
  open_authoring: true # accept contributions (forks) from GitHub users
  branch: master
  squash_merges: true # squash all commits into a single commit when the PR is merged
  commit_messages:
    create: 'New {{collection}}: "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: '{{message}}, {{author-login}}'

# Enables the NetlifyCMS editorial workflow tools
publish_mode: editorial_workflow

# Media / Images
# This is where media will be stored in the repo
media_folder: "media"
# Path for uploaded media on the live site
public_folder: "media"

# slug — sets how filenames for entries are created and sanitized.
slug:
  encoding: "unicode"
  clean_accents: true


# Localhost Editing
# uses the local proxy server port
# see our package.json for how to include this into build scripts
local_backend:
  url: http://localhost:8081/api/v1

# Content Collections
collections:

  # AUTHORS =======================
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    label_singular: 'Page'
    description: "TKTK"
    folder: "_pages" # path to the folder where files are stored
    # path: '{{slug}}/_index' # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"
        hint: "TKTK"

      - label: "Deck"
        name: "deck"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Summary"
        name: "summary"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        hint: "TKTK"
        required: false
